### ISSUE TITLE
Error adding Prometheus data source to Grafana

### ISSUE THREAD

**Issue by Joao-Rocha-ISTEC** [kennethprose/Foptimum#1]
I'm having the following error adding the Prometheus server to Grafana:

Error reading Prometheus: 

bad_response: readObjectStart: expect { or n, but found #, error found in #1 byte of ...|# HELP pyth|..., bigger context ...|# HELP python_gc_objects_collected_total Objects co|...

Here's the configs in Grafana:
![image](https://user-images.githubusercontent.com/79578585/192106448-ec34e757-6643-4967-ad4e-4b6b133613ee.png)

Using a docker container, in Unraid server.

**Comment by kennethprose** [comment]
Hi,

Based on the port number you specified in the URL, it looks like you are adding the Foptimum container as a data source.

I should have been more clear in the documentation. The Foptimum container exports data that a Prometheus **_server_** can read. That Prometheus **_server_** is what you need to add as a data source in Grafana. So the flow of data is Foptimum -> Prometheus Server -> Grafana.

Since you are running unRAID, install the Prometheus docker container from the community apps store. You will need to add the IP of Foptimum as a target in Prometheus by modifying the prometheus.yml config file located at /mnt/user/appdata/prometheus/etc. If done correctly, you will see the IP appear as a target in the Prometheus WebUI:

![image](https://user-images.githubusercontent.com/32115575/192109218-3cb9e545-a80d-4afa-a114-e05ac7d54bfb.png)

Then, you can add the Prometheus server, which usually runs on port 9090, as a data source in Grafana:

![image](https://user-images.githubusercontent.com/32115575/192109308-fa5ac4f0-d52d-4f6a-9092-202ae87a49ec.png)

I remember finding very little documentation on Prometheus when I first set it up, so if you have any more questions, feel free to ask.

**Comment by ctchickenman** [comment]
Can you please update the documentation to reflect this comment as well as post a sample prometheus.yml? While this post is clear, I have no idea what that prometeus.yml should look like.

**Comment by kennethprose** [comment]
I am by no means an expert in Prometheus, but here is a config that is working for me:

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: foptimum
    static_configs:
      - targets: ["10.10.10.10:9191"]
```
